name: 'Emacs Lisp check'

description: |
  Run a number of different Emacs Lisp checks.

inputs:
  check:
    description: |
      Emacs Lisp check to execute.
      Consult the README for supported checks.
    default: 'melpa'
  file:
    description: |
      Entry file for Emacs Lisp check.
      Basic globbing is supported.
    default: '*.el'
  ignore_warnings:
    description: |
      Whether to ignore warnings.
    default: false
  warnings_as_errors:
    description: |
      Whether to treat errors as warnings.
    default: false

runs:
  using: 'composite'
  steps:
    - run: >-
        emacs
        --no-site-file --batch
        --eval (setq debug-on-error t)
        --load elisp-check.el
        --eval (setq elisp-check-ignore-warnings ${{ inputs.ignore_warnings }})
        --eval (setq elisp-check-warnings-as-errors ${{ inputs.warnings_as_errors }})
        --eval (elisp-check-run "${{ inputs.check }}" "${{ inputs.file }}" t)
      shell: 'bash'

branding:
  icon: 'align-left'
  color: 'purple'
